version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employeee_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeee_db
      MYSQL_USER: employeee_user
      MYSQL_PASSWORD: employeee_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - employeee_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: employeee_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - employeee_network

volumes:
  mysql_data:

networks:
  employeee_network:
    driver: bridge
